<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>

    <IsPackable>false</IsPackable>

    <NoWin32Manifest>true</NoWin32Manifest>

    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>../myoddweb.directorywatcher.snk</AssemblyOriginatorKeyFile>

  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <OutputPath>..\bin\Debug\</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <OutputPath>..\bin\Release\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="nunit" Version="3.14.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="6.3.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\myoddweb.directorywatcher\myoddweb.directorywatcher.csproj" />
  </ItemGroup>

</Project>
