<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>A fast and reliable, (non blocking!), .NET File/Directory watcher, complete rewrite of FileSystemWatcher to ensure speed/accuracy/reliability/suppress duplicate events</Description>
    <VersionPrefix>0.2.0</VersionPrefix>
    <TargetFrameworks>net462;netstandard2.0;net8.0</TargetFrameworks>
    <LangVersion>latest</LangVersion>

    <AssemblyName>MyOddWeb.DirectoryWatcher.Interfaces</AssemblyName>
    <PackageId>MyOddWeb.DirectoryWatcher.Interfaces</PackageId>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>../myoddweb.directorywatcher.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <OutputPath>$(SolutionDir)bin\Release\</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <OutputPath>$(SolutionDir)bin\Debug\</OutputPath>
  </PropertyGroup>

 <ItemGroup Condition=" '$(TargetFramework)' == 'net462'">
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.Data" />
    <Reference Include="Microsoft.CSharp" />
  </ItemGroup>

  <PropertyGroup Condition=" '$(TargetFramework)' == 'netstandard2.0' Or '$(TargetFramework)' == 'net8.0' ">
    <DefineConstants>$(DefineConstants);CORECLR</DefineConstants>
  </PropertyGroup>

</Project>
